vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        suite_images:
            uri_prefix: '/images'
            upload_destination: '%kernel.project_dir%/public/images'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
