vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        suite_thumbnails:
            uri_prefix: '/images/thumbnails'
            upload_destination: '%kernel.project_dir%/public/images/thumbnails'
        suite_images:
            uri_prefix: '/images/attachments'
            upload_destination: '%kernel.project_dir%/public/images/attachments'
