<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => 'a662409bdcd383b398cf4dd3f77e49f7',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'DATABASE_URL' => 'mysql://bcb56c2d0faf0d:4fb0cb8d@eu-cdbr-west-02.cleardb.net/heroku_c5444425cd64b09?reconnect=true',
);
