<?php

namespace App\Controller\Admin;

use App\Entity\User;
use EasyCorp\Bundle\EasyAdminBundle\Config\Actions;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Config\Filters;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\ArrayField;
use EasyCorp\Bundle\EasyAdminBundle\Field\ChoiceField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class UserCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return User::class;
    }

    public function configureCrud(Crud $crud): Crud
    {
        return $crud
            ->renderContentMaximized()
            ->setEntityLabelInSingular('User')
            ->setEntityLabelInSingular('Users')
            ->setEntityPermission('ROLE_ADMIN')
            ->setSearchFields(['email', 'firstname', 'lastname'])
            ->setDefaultSort(['id' => 'DESC']);
    }

    public function configureFilters(Filters $filters): Filters
    {
        $filters->add('id');
        $filters->add('email');
        return parent::configureFilters($filters); // TODO: Change the autogenerated stub
    }

    public function configureFields(string $pageName): iterable
    {
        $roles = ['ROLE_ADMIN'];
        return [
            TextField::new('email', 'Email'),
            TextField::new('password', 'Mot de passe')->onlyWhenCreating(),
            TextField::new('firstname', 'Prénom'),
            TextField::new('lastname', 'Nom'),
            ChoiceField::new('roles', 'Roles')
                ->setChoices(array_combine($roles, $roles))
                ->allowMultipleChoices()
                ->renderExpanded()
        ];
    }

    public function configureActions(Actions $actions): Actions
    {
        return $actions->add(Crud::PAGE_INDEX, 'detail');
    }
}
